(package "recentf-excl"
         "0.1.0"
         "Exclude commands for recent files")

(website-url "https://github.com/jcs-elpa/recentf-excl")
(keywords "excl" "exclude" "recentf")

(package-file "recentf-excl.el")

(source "gnu")
(source "melpa")

(depends-on "emacs" "26.1")

(setq network-security-level 'low)  ; see https://github.com/jcs090218/setup-emacs-windows/issues/156#issuecomment-932956432
